# Generated by Django 5.0.4 on 2024-07-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_blood_type_item_citizenship_item_civil_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='mothers_first_name',
            new_name='mothers_maiden_first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mothers_last_name',
            new_name='mothers_maiden_last_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mothers_middle_name',
            new_name='mothers_maiden_middle_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=20),
        ),
    ]
